apiVersion: v1
kind: Service
metadata:
  name: paginaeducacion-service
spec:
  type: NodePort
  selector:
    app: paginaeducacion
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000 